name: Telegram Pull Request Notifier

on:
  pull_request:
    types: [opened, review_requested]

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
      # Send a telegram message on pr open or review request
      - name: Pull Request Telegram
        uses: F2had/pr-telegram-action@v1.0.0
        with: 
          bot_token: '7087056526:AAFajWYHT5o7h2ABmI-sFJoiuRZcXJ_r3EQ'
          chat_id: '-1002104613164'
